### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by monomadic** [git-moss/Kontakt-File-Format#3]
Hi, not sure of the best way to get in touch with you, tried various ways, please feel free to close this issue once read.

Seems you have been following some of the older findings / schematics I'd reversed from the NI formats - I've got much newer findings not yet in the code and it seems we now have some overlap. Would be good to make contact.

deathdisco on telegram, unless you have a preference?

**Comment by git-moss** [comment]
I am not on Telegram. Are you on KVR?
